env:
  es6: true
  node: true

extends:
  - 'plugin:@urbandoor/urbandoor/common'

overrides:
  - files:
      - "features/**/*.js"
      - "wdio.conf.js"
    env:
      "webdriverio/wdio": true
    rules:
      new-cap:
        - error
        - capIsNewExceptions:
            - And
            - Given
            - Then
            - When

parserOptions:
  ecmaVersion: 2018

plugins:
  - webdriverio
