env:
  es6: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:compat/recommended"
  - "plugin:eslint-comments/recommended"
  - "plugin:vue/recommended"
  # The prettier plugin should always be last so it can disable other rules
  - "plugin:prettier/recommended"

overrides:
  - files:
      - "src/**/*.js"
    env:
      browser: true
    rules:
      no-console: error

  - files:
      - "features/**/*.js"
      - "wdio.conf.js"
    env:
      "webdriverio/wdio": true
    rules:
      compat/compat: off

parserOptions:
  ecmaVersion: 2017

plugins:
  - webdriverio

rules:
  arrow-body-style:
    - error
    - as-needed
  arrow-parens:
    - error
    - always
  quotes:
    - error
    - single
    - avoidEscape: true
  strict:
    - error
    - safe
  eslint-comments/no-unused-disable: error
  no-invalid-this: error
  no-warning-comments: warn
  valid-jsdoc:
    - error
    - prefer:
        arg: "param"
        argument: "param"
        fires: "emits"
        return: "returns"
        virtual: "abstract"
      preferType:
        object: "Object"
        function: "Function"
        Boolean: "boolean"
        Number: "number"
        String: "string"
      requireParamType: true
      requireReturn: false
      requireReturnType: true
      requireParamDescription: false
      requireReturnDescription: false

  # lazies
  no-console:
    - off

  # force es6 behaviors
  no-template-curly-in-string: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-object-spread: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error

settings:
  polyfills:
    - fetch
