verifyConditions:
  - condition-circle
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
prepare:
  - '@semantic-release/changelog'
  -
    path: '@semantic-release/exec'
    cmd: "npm run build"
  - '@semantic-release/npm'
publish:
  - '@semantic-release/npm'
