extends:
  - 'plugin:@urbandoor/urbandoor/modern'

globals:
  # set process as a global rather than using env: node so that we can use
  # process.env without other assumptions
  process: false

settings:
  polyfills:
    - fetch
